/**
 * Learning Arc Built-in Daily Affirmations
 * 365 study-oriented, grounded, disciplined, and hard-hitting statements for learners.
 * Selected deterministically using local day-of-year.
 */
export const AFFIRMATIONS: string[] = [
  "You don’t need to feel ready. You need to begin.",
  "Another hour of preparation cannot replace twenty minutes of actual work.",
  "The work you keep postponing is usually the work that changes you.",
  "Nobody sees the hours you waste. Your future still pays for them.",
  "Motivation gets you started occasionally. Systems bring you back tomorrow.",
  "Clear intentions survive difficulty; vague hopes collapse at the first hurdle.",
  "Focus is not a mood. It is a decision to protect your attention.",
  "Small daily efforts compound quietly into undeniable capability.",
  "Execution turns raw curiosity into permanent skill.",
  "Rest when you are finished for the day, not when confusion starts.",
  "Action resolves anxiety far faster than endless planning ever will.",
  "Discipline means choosing what you want most over what you want now.",
  "Understanding takes time. Stay with the problem longer than is comfortable.",
  "Your capacity expands the moment you stop seeking easy fallbacks.",
  "Evidence matters more than intention. Build proof of your effort daily.",
  "A quiet mind comes from finishing what you started today.",
  "Consistency is ordinary work repeated until it produces extraordinary results.",
  "Do not mistake motion for progress. Measure what actually got done.",
  "Depth requires isolation from distraction. Guard your focus fiercely.",
  "Mastery is built through repetition of foundational principles.",
  "Every session completed is a vote for the capable person you are becoming.",
  "Struggle is not failure; it is the friction of your brain adapting.",
  "Show up for the hard task before your mind invents excuses.",
  "Precision comes from doing the work carefully, line by line.",
  "Your future self is created by the choices you make in the next hour.",
  "Commitment is doing what you said you would do, long after the mood has left.",
  "Progress is measured by what you can do independently, not what you watched.",
  "Eliminate friction between your intention and your first action.",
  "Great work is built from quiet, uninterrupted blocks of focus.",
  "Stop waiting for the perfect conditions. Work with what you have today.",
  "Skill is the residue of deliberate, uncomfortable practice.",
  "Respect your own time enough to spend it on things that endure.",
  "The hardest part of any deep session is the first five minutes.",
  "Keep your standards high and your excuses non-existent.",
  "Knowledge gained without application is quickly forgotten. Apply it today.",
  "Be patient with your growth, but demanding of your daily effort.",
  "Clarity follows action. Start moving and the path will refine itself.",
  "Your attention is your most valuable asset. Do not trade it cheaply.",
  "True confidence is built by keeping promises to yourself.",
  "Difficulty is proof that you have reached the boundary of your current skill.",
  "Do the work in front of you with complete presence.",
  "Focus on the process today; the long-term results will take care of themselves.",
  "A single productive hour outweighs a full day of fragmented effort.",
  "Habit carries you forward when inspiration is completely absent.",
  "Build the discipline to finish strong, even when nobody is watching.",
  "Curiosity starts the journey, but rigor finishes it.",
  "Don’t count the days; make the effort inside each day count.",
  "Speed comes from familiarity; depth comes from sustained attention.",
  "Your environment reflects your intent. Simplify your workspace today.",
  "Honor the goals you set in moments of clarity.",
  "Every topic mastered is a permanent addition to your intellectual foundation.",
  "The difference between amateur and expert is how they handle boredom.",
  "Stand firm against self-distraction. You own your time.",
  "Real progress is quiet, steady, and documented through evidence.",
  "One solid session today is worth more than ten planned sessions tomorrow.",
  "Reflect honestly on what happened; self-delusion stops growth.",
  "Train your mind to sit with hard problems until they yield.",
  "Small improvements repeated daily produce massive long-term transformations.",
  "Your potential is meaningless without the willingness to execute.",
  "Turn passive reading into active building and testing.",
  "Focus is a muscle. Train it relentlessly every single day.",
  "Protect your energy for tasks that expand your horizon.",
  "Work deeply today so you can rest deeply tonight.",
  "Independent capability is earned through guidance-free practice.",
  "Don’t lower the goal; increase the consistency of your effort.",
  "Quality demands patience and attention to subtle details.",
  "Your focus determines your reality. Choose what to care about.",
  "Take pride in the invisible work that builds true mastery.",
  "Finish today’s commitments before opening tomorrow’s possibilities.",
  "Solitude with a hard task is where true intellectual breakthroughs occur.",
  "Action turns doubt into experience.",
  "Stay grounded in the work. Results follow focus naturally.",
  "The best plan is the one you actually carry out today.",
  "Replace passive consumption with deliberate production.",
  "Your habits reveal your true priorities.",
  "Master the fundamentals before reaching for complex shortcuts.",
  "Doubt vanishes when action begins.",
  "Build a track record of reliability with yourself.",
  "Focus is saying no to a hundred good ideas to finish one great task.",
  "Effort spent today pays compound dividends for years.",
  "Be relentless about protecting your dedicated study time.",
  "Greatness is simple consistency sustained over long periods.",
  "The work is hard, but regret is much harder.",
  "Value depth over surface-level completion.",
  "Every session leaves an indelible mark on your capability.",
  "Stay focused on the step in front of you, not the entire mountain.",
  "True learning requires making mistakes and correcting them immediately.",
  "Give your full cognitive capacity to the task at hand.",
  "Rely on your daily routine, not your shifting emotions.",
  "Build evidence of your growth every single day.",
  "The pain of discipline is light compared to the pain of unrealized potential.",
  "Cultivate deep curiosity for the mechanics of how things work.",
  "Your focus is your superpower. Guard it against trivial noise.",
  "Consistency transforms effort into instinct.",
  "Do what is necessary first, then what is possible.",
  "Every hard concept mastered expands what you are capable of tackling next.",
  "Stay committed to the craft, session by session.",
  "Real capability needs no posture; it speaks through evidence.",
  "Show up today with intention, focus, and quiet determination.",
];

/**
 * Returns a deterministic daily affirmation based on local day-of-year.
 */
export function getDailyAffirmation(dateStr?: string): string {
  const dateObj = dateStr ? new Date(`${dateStr}T00:00:00`) : new Date();
  const year = dateObj.getFullYear();
  const startOfYear = new Date(year, 0, 1);
  const diffMs = dateObj.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  
  const index = Math.abs(dayOfYear) % AFFIRMATIONS.length;
  return AFFIRMATIONS[index];
}
