export const MODES = ["Learning", "Practicing", "Building", "Reading", "Revising", "Other"] as const;
export type Mode = typeof MODES[number];
export type Independence = "Following a tutorial" | "With significant guidance" | "With some guidance" | "Mostly independently" | "Completely independently";
export type Goal = { title: string; description?: string; duration: string; createdAt: string };
export type Analysis = { summary: string; skills: string[]; classification: "guided" | "practice" | "application" | "exploration"; evidence: "low" | "medium" | "high"; progression: string; concern?: string; nextAction: string };
export type Session = { id: string; startedAt: string; completedAt: string; duration: number; mode: Mode; topic: string; intent?: string; reflection: string; independence: Independence; difficulty?: string; analysis?: Analysis; analysisError?: boolean };
export type Report = { createdAt: string; narrative: string; priority: string; pattern: string; gap: string };
export type Store = { version: 1; goal?: Goal; sessions: Session[]; report?: Report };
export const EMPTY: Store = { version: 1, sessions: [] };
const key = "learning-arc-v1";
export function load(): Store { try { const p = JSON.parse(localStorage.getItem(key) || "null"); return p && p.version === 1 && Array.isArray(p.sessions) ? p : EMPTY; } catch { return EMPTY; } }
export function save(data: Store) { localStorage.setItem(key, JSON.stringify(data)); }
export function localDay(iso: string) { const d = new Date(iso); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
export function minutes(n: number) { const h = Math.floor(n / 60); return h ? `${h}h ${n % 60}m` : `${n}m`; }
export function stats(sessions: Session[]) {
 const done = sessions.filter(s => s.completedAt); const total = done.reduce((n,s)=>n+s.duration,0); const today = localDay(new Date().toISOString());
 const daily = Object.fromEntries(done.map(s=>[localDay(s.completedAt),0] as [string,number])); done.forEach(s=>daily[localDay(s.completedAt)] += s.duration);
 let streak=0; const d=new Date(); while(daily[localDay(d.toISOString())]) { streak++; d.setDate(d.getDate()-1); }
 const byMode = Object.fromEntries(MODES.map(m=>[m,done.filter(s=>s.mode===m).reduce((n,s)=>n+s.duration,0)]));
 const top = Object.entries(done.reduce<Record<string,number>>((a,s)=>{a[s.topic]=(a[s.topic]||0)+s.duration;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
 return { done,total,today:daily[today]||0,week:done.filter(s=>Date.now()-new Date(s.completedAt).getTime()<6048e5).reduce((n,s)=>n+s.duration,0),streak,daily,byMode,top };
}
export function validateImport(value: unknown): value is Store { return !!value && typeof value === "object" && (value as Store).version === 1 && Array.isArray((value as Store).sessions); }
export function seed(): Store {
 const now = new Date(); const items: Array<[number,Mode,string,number,Independence,string,string]> = [
 [20,"Learning","HTML & CSS",45,"Following a tutorial","Built a responsive profile card while following a lesson.","Found flexbox alignment confusing."], [18,"Practicing","JavaScript basics",50,"With some guidance","Solved array and function exercises from memory.","Needed to revisit callbacks."], [16,"Learning","DOM manipulation",45,"Following a tutorial","Watched a DOM events lesson and recreated examples.","Remembering selectors."], [13,"Practicing","DOM manipulation",50,"Mostly independently","Built a small task list with add and delete actions.","Keeping state in sync."], [10,"Learning","Async JavaScript",50,"Following a tutorial","Learned promises and async await with guided fetch examples.","Error handling."], [7,"Practicing","Async JavaScript",50,"With some guidance","Rebuilt a weather request exercise without the video.","Parsing API responses."], [4,"Building","Movie API project",60,"Mostly independently","Created search, loading, empty and error states with a public movie API.","Handling missing poster images."], [2,"Building","Movie API project",50,"Completely independently","Improved the movie search project and deployed a clean version.","Refactoring repeated UI code."] ];
 const sessions = items.map(([days,mode,topic,duration,independence,reflection,difficulty],i)=>{ const end=new Date(now); end.setDate(now.getDate()-days); end.setHours(10+i%5,0,0,0); const application=mode==="Building"; return {id:`demo-${i}`,startedAt:new Date(end.getTime()-duration*60000).toISOString(),completedAt:end.toISOString(),duration,mode,topic,intent:"Grow into an independent full-stack developer",reflection,independence,difficulty,analysis:{summary:application?`Applied ${topic} through an independently-directed project increment.`:`Developed ${topic} through ${mode.toLowerCase()} work.`,skills:[topic, ...(topic.includes("API")?["APIs","Async JavaScript"]:[])],classification:application?"application":mode==="Practicing"?"practice":"guided",evidence:application?"high":mode==="Practicing"?"medium":"low",progression:application?"Strong evidence of applying knowledge independently.":"A useful step toward application.",concern:mode==="Learning"?"Guided exposure is strongest when followed by a self-directed task.":undefined,nextAction:application?"Write down one reusable pattern from this build.":"Build a small variation without the lesson open."}} as Session; });
 return {version:1,goal:{title:"Become a Full-Stack Developer",description:"Move from tutorials to independently shipping useful web applications.",duration:"90 days",createdAt:now.toISOString()},sessions,report:{createdAt:now.toISOString(),narrative:"Your journey shows a credible shift from guided foundations into independent application. Async JavaScript and APIs now appear as connected, repeated evidence—not isolated lessons.",pattern:"Learning made up the early arc; recent sessions have moved toward practice and building.",gap:"Turn the movie project into one more self-directed feature before starting another course.",priority:"Build one API feature from a blank file, then explain the decisions you made."}};
}
